/**
 * KC EVENT - GALLERY DATA
 * Ảnh tối ưu (WebP, nhiều kích thước) trong assets/img/du-an-*.
 */
const galleryItems = [
  {
    "id": "gala-ntx",
    "category": "gala",
    "categoryName": "Gala Dinner",
    "title": "Gala Dinner NTX Group - Together We Shine",
    "client": "NTX Group",
    "location": "Hạ Long, Quảng Ninh",
    "src": "assets/img/du-an-gala-ntx-800.webp",
    "full": "assets/img/du-an-gala-ntx-1600.webp",
    "srcset": "assets/img/du-an-gala-ntx-480.webp 480w, assets/img/du-an-gala-ntx-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Tổ chức Gala Dinner Company Trip NTX Group chuyên nghiệp bởi KC Event"
  },
  {
    "id": "khoi-cong-genesis",
    "category": "event",
    "categoryName": "Sự Kiện & Khởi Công",
    "title": "Lễ Khởi Công Dự Án TT Genesis",
    "client": "Ricons Construction & TT Capital",
    "location": "TP. Hồ Chí Minh",
    "src": "assets/img/du-an-khoi-cong-genesis-800.webp",
    "full": "assets/img/du-an-khoi-cong-genesis-1600.webp",
    "srcset": "assets/img/du-an-khoi-cong-genesis-480.webp 480w, assets/img/du-an-khoi-cong-genesis-800.webp 800w",
    "width": 1600,
    "height": 900,
    "alt": "Tổ chức Lễ Khởi công dự án TT Genesis Ricons quy mô chuyên nghiệp"
  },
  {
    "id": "tb-hatu-beach",
    "category": "teambuilding",
    "categoryName": "Team Building",
    "title": "Team Building Bãi Biển - Gắn Kết Để Bứt Phá",
    "client": "Hatu Group",
    "location": "Bãi biển Resort cao cấp",
    "src": "assets/img/du-an-tb-hatu-beach-800.webp",
    "full": "assets/img/du-an-tb-hatu-beach-1600.webp",
    "srcset": "assets/img/du-an-tb-hatu-beach-480.webp 480w, assets/img/du-an-tb-hatu-beach-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Tổ chức Team Building bãi biển cho tập đoàn Hatu Group sôi động"
  },
  {
    "id": "khoi-cong-ducviet",
    "category": "event",
    "categoryName": "Sự Kiện & Khởi Công",
    "title": "Lễ Khởi Công Bệnh Viện Đa Khoa Đức Việt",
    "client": "Bệnh Viện Đa Khoa Đức Việt",
    "location": "Hà Nội",
    "src": "assets/img/du-an-khoi-cong-ducviet-800.webp",
    "full": "assets/img/du-an-khoi-cong-ducviet-1600.webp",
    "srcset": "assets/img/du-an-khoi-cong-ducviet-480.webp 480w, assets/img/du-an-khoi-cong-ducviet-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Lễ Khởi công Bệnh viện Đa khoa Đức Việt quy mô lớn tại Hà Nội"
  },
  {
    "id": "nghi-thuc-ducviet",
    "category": "event",
    "categoryName": "Sự Kiện & Khởi Công",
    "title": "Nghi Thức Động Thổ & Múa Lân Khởi Công",
    "client": "Bệnh Viện Đa Khoa Đức Việt",
    "location": "Hà Nội",
    "src": "assets/img/du-an-nghi-thuc-ducviet-800.webp",
    "full": "assets/img/du-an-nghi-thuc-ducviet-1600.webp",
    "srcset": "assets/img/du-an-nghi-thuc-ducviet-480.webp 480w, assets/img/du-an-nghi-thuc-ducviet-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Nghi thức xúc cát động thổ và múa lân sư rồng cầu may mắn"
  },
  {
    "id": "khai-truong-vinfast",
    "category": "event",
    "categoryName": "Sự Kiện & Khởi Công",
    "title": "Grand Opening Showroom VinFast Quốc Tế",
    "client": "VinFast Thanh Hà",
    "location": "Khu đô thị Thanh Hà, Hà Nội",
    "src": "assets/img/du-an-khai-truong-vinfast-800.webp",
    "full": "assets/img/du-an-khai-truong-vinfast-1600.webp",
    "srcset": "assets/img/du-an-khai-truong-vinfast-480.webp 480w, assets/img/du-an-khai-truong-vinfast-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Lễ Khai trương Showroom VinFast Quốc Tế Thanh Hà hoành tráng"
  },
  {
    "id": "khai-truong-lotteria",
    "category": "event",
    "categoryName": "Sự Kiện & Khởi Công",
    "title": "Khai Trương Cửa Hàng Lotteria Goldmark City",
    "client": "Lotteria Việt Nam",
    "location": "Tòa ROX Center, Hà Nội",
    "src": "assets/img/du-an-khai-truong-lotteria-800.webp",
    "full": "assets/img/du-an-khai-truong-lotteria-1600.webp",
    "srcset": "assets/img/du-an-khai-truong-lotteria-480.webp 480w, assets/img/du-an-khai-truong-lotteria-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Lễ khai trương cửa hàng ẩm thực Lotteria tại khu đô thị Goldmark City"
  },
  {
    "id": "gala-catba",
    "category": "travel",
    "categoryName": "Tour Du Lịch",
    "title": "Tour Company Trip & Gala Dinner Cát Bà",
    "client": "Trường Thịnh Logistics",
    "location": "Đảo Ngọc Cát Bà, Hải Phòng",
    "src": "assets/img/du-an-gala-catba-800.webp",
    "full": "assets/img/du-an-gala-catba-1600.webp",
    "srcset": "assets/img/du-an-gala-catba-480.webp 480w, assets/img/du-an-gala-catba-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Tour du lịch Cát Bà kết hợp Gala Dinner Chạm Sóng Chạm Yêu Thương"
  },
  {
    "id": "banquet-setup",
    "category": "gala",
    "categoryName": "Gala Dinner",
    "title": "Không Gian Tiệc Gala Đẳng Cấp 5 Sao",
    "client": "Khách Sạn & Trung Tâm Hội Nghị",
    "location": "Ballroom cao cấp",
    "src": "assets/img/du-an-banquet-setup-800.webp",
    "full": "assets/img/du-an-banquet-setup-1600.webp",
    "srcset": "assets/img/du-an-banquet-setup-480.webp 480w, assets/img/du-an-banquet-setup-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Setup bàn tiệc Gala Dinner phong cách quý phái sang trọng"
  },
  {
    "id": "yep-iscvina",
    "category": "gala",
    "categoryName": "Gala Dinner",
    "title": "Year End Party - Nhiệt Huyết ISCVina",
    "client": "ISC Vina",
    "location": "Phú Thọ",
    "src": "assets/img/du-an-yep-iscvina-800.webp",
    "full": "assets/img/du-an-yep-iscvina-1600.webp",
    "srcset": "assets/img/du-an-yep-iscvina-480.webp 480w, assets/img/du-an-yep-iscvina-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Backdrop 3D ấn tượng Year End Party công ty ISC Vina"
  },
  {
    "id": "tb-pvchem",
    "category": "teambuilding",
    "categoryName": "Team Building",
    "title": "Ngày Hội Thể Thao PVChem 35 Năm",
    "client": "PetroVietnam PVChem",
    "location": "Flamingo Đại Lải Resort",
    "src": "assets/img/du-an-tb-pvchem-800.webp",
    "full": "assets/img/du-an-tb-pvchem-1600.webp",
    "srcset": "assets/img/du-an-tb-pvchem-480.webp 480w, assets/img/du-an-tb-pvchem-800.webp 800w",
    "width": 1600,
    "height": 1067,
    "alt": "Giải đấu giao lưu thể thao Pickleball kỷ niệm 35 năm PetroVietnam PVChem"
  },
  {
    "id": "tb-outdoor-plaza",
    "category": "teambuilding",
    "categoryName": "Team Building",
    "title": "Team Building Quảng Trường 500+ Khách",
    "client": "Tập Đoàn Đa Quốc Gia",
    "location": "Khu du lịch sinh thái",
    "src": "assets/img/du-an-tb-outdoor-plaza-800.webp",
    "full": "assets/img/du-an-tb-outdoor-plaza-1600.webp",
    "srcset": "assets/img/du-an-tb-outdoor-plaza-480.webp 480w, assets/img/du-an-tb-outdoor-plaza-800.webp 800w",
    "width": 1276,
    "height": 956,
    "alt": "Quy mô Team Building ngoài trời hơn 500 thành viên đồng phục xanh"
  },
  {
    "id": "hoi-nghi-vars",
    "category": "event",
    "categoryName": "Sự Kiện & Khởi Công",
    "title": "Hội Nghị Bất Động Sản Quốc Gia VARS Awards",
    "client": "Strantech & VARS",
    "location": "Trung tâm hội nghị quốc gia",
    "src": "assets/img/du-an-hoi-nghi-vars-800.webp",
    "full": "assets/img/du-an-hoi-nghi-vars-1600.webp",
    "srcset": "assets/img/du-an-hoi-nghi-vars-480.webp 480w, assets/img/du-an-hoi-nghi-vars-800.webp 800w",
    "width": 1280,
    "height": 960,
    "alt": "Không gian sảnh check-in sang trọng Ngày hội môi giới bất động sản VARS"
  },
  {
    "id": "san-khau-sondong",
    "category": "event",
    "categoryName": "Sự Kiện & Khởi Công",
    "title": "Lễ Kỷ Niệm 20 Năm Nhiệt Điện Sơn Động TKV",
    "client": "Tổng Công Ty Điện Lực - TKV",
    "location": "Bắc Giang",
    "src": "assets/img/du-an-san-khau-sondong-800.webp",
    "full": "assets/img/du-an-san-khau-sondong-1600.webp",
    "srcset": "assets/img/du-an-san-khau-sondong-480.webp 480w, assets/img/du-an-san-khau-sondong-800.webp 800w",
    "width": 1600,
    "height": 900,
    "alt": "Thiết kế sân khấu kỷ niệm 20 năm thành lập Công ty Nhiệt điện Sơn Động TKV"
  },
  {
    "id": "teabreak-catering",
    "category": "event",
    "categoryName": "Sự Kiện & Khởi Công",
    "title": "Tiệc Ngọt Teabreak Khách Hàng Cao Cấp",
    "client": "Showroom Auto Launch",
    "location": "Hà Nội",
    "src": "assets/img/du-an-teabreak-catering-800.webp",
    "full": "assets/img/du-an-teabreak-catering-1600.webp",
    "srcset": "assets/img/du-an-teabreak-catering-480.webp 480w, assets/img/du-an-teabreak-catering-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Bàn tiệc ngọt teabreak hoa tươi và bánh ngọt cao cấp phục vụ sự kiện"
  },
  {
    "id": "gala-art-performance",
    "category": "gala",
    "categoryName": "Gala Dinner",
    "title": "Tiết Mục Biểu Diễn Nghệ Thuật Đêm Gala",
    "client": "Doanh Nghiệp Trẻ",
    "location": "Sân khấu trung tâm",
    "src": "assets/img/du-an-gala-art-performance-800.webp",
    "full": "assets/img/du-an-gala-art-performance-1600.webp",
    "srcset": "assets/img/du-an-gala-art-performance-480.webp 480w, assets/img/du-an-gala-art-performance-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Chương trình nghệ thuật và âm nhạc bùng nổ sân khấu tiệc công ty"
  },
  {
    "id": "yep-traditional",
    "category": "gala",
    "categoryName": "Gala Dinner",
    "title": "Tiệc Tất Niên Tri Ân & Trao Thưởng",
    "client": "Doanh Nghiệp Xuất Sắc",
    "location": "Khuôn viên sự kiện",
    "src": "assets/img/du-an-yep-traditional-800.webp",
    "full": "assets/img/du-an-yep-traditional-1600.webp",
    "srcset": "assets/img/du-an-yep-traditional-480.webp 480w, assets/img/du-an-yep-traditional-800.webp 800w",
    "width": 1600,
    "height": 1066,
    "alt": "Không khí tưng bừng trao giải và tri ân tiệc tất niên doanh nghiệp"
  },
  {
    "id": "tb-action-energy",
    "category": "teambuilding",
    "categoryName": "Team Building",
    "title": "Thử Thách Vượt Chướng Ngại Vật Đồng Đội",
    "client": "Khách Đoàn Doanh Nghiệp",
    "location": "Khu dã ngoại sinh thái",
    "src": "assets/img/du-an-tb-action-energy-800.webp",
    "full": "assets/img/du-an-tb-action-energy-1600.webp",
    "srcset": "assets/img/du-an-tb-action-energy-480.webp 480w, assets/img/du-an-tb-action-energy-800.webp 800w",
    "width": 1276,
    "height": 956,
    "alt": "Trò chơi teambuilding đối kháng kích thích tinh thần lãnh đạo"
  }
];
